apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "argus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argus.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "argus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: {{ include "argus.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "argus.fullname" . }}-env
            {{- if .Values.secret.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /readyz, port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: {{ .Values.service.targetPort }} }
            initialDelaySeconds: 60
            periodSeconds: 15
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "argus.fullname" . }}-data
      {{- end }}
