apiVersion: v1
kind: Service
metadata:
  name: {{ include "argus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "argus.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
